export const DEFAULT_LINKS = [
  { title: 'Chinese Grammar Wiki — HSK1', url: 'https://resources.allsetlearning.com/chinese/grammar/HSK_1_grammar_points', cat: 'Grammar' },
  { title: 'Chinese Grammar Wiki — HSK2', url: 'https://resources.allsetlearning.com/chinese/grammar/HSK_2_grammar_points', cat: 'Grammar' },
  { title: 'HSK2 vocab + sentences (StudyCLI)', url: 'https://studycli.org/chinese-tools/hsk-2-vocabulary/', cat: 'Vocabulary' },
  { title: 'HSK2 vocab + audio (HSK Academy)', url: 'https://hsk.academy/en/hsk-2-vocabulary-list', cat: 'Vocabulary' },
  { title: 'HSK2 vocab PDF (Chill Chinese)', url: 'https://chill-chinese.com/hsk-2-vocabulary-list.pdf', cat: 'Vocabulary' },
  { title: 'Comprehensible Chinese (YouTube)', url: 'https://www.youtube.com/results?search_query=comprehensible+chinese', cat: 'Video' },
  { title: 'DaShu Mandarin (YouTube)', url: 'https://www.youtube.com/results?search_query=dashu+mandarin', cat: 'Video' },
  { title: 'Grace Mandarin Chinese (YouTube)', url: 'https://www.youtube.com/results?search_query=grace+mandarin+chinese', cat: 'Video' },
  { title: 'ChinesePod (Spotify search)', url: 'https://open.spotify.com/search/ChinesePod', cat: 'Podcast' },
  { title: 'Coffee Break Chinese (Spotify search)', url: 'https://open.spotify.com/search/Coffee%20Break%20Chinese', cat: 'Podcast' },
  { title: 'iTalki — 1-on-1 speaking practice', url: 'https://www.italki.com/', cat: 'Tool' },
  { title: 'HelloTalk — language exchange', url: 'https://www.hellotalk.com/', cat: 'Tool' },
  { title: 'Mandarin Companion — graded readers', url: 'https://mandarincompanion.com/', cat: 'Tool' },
  { title: 'Mandarin tone pair drills (search)', url: 'https://www.google.com/search?q=mandarin+tone+pair+drills+audio', cat: 'Tool' },
];

export const ROADMAP = [
  {
    month: 'Month 1', title: 'Foundations — HSK1 grammar solid, HSK2 begins',
    weeks: [
      { label: 'Week 1', items: [
        'Grammar: HSK1 grammar points #1–15 (Grammar Wiki) — 2–3 points/day, write 3 sentences per point',
        'Vocab: Start HSK2 list, 20–25 new words — each in a sentence immediately',
        'Tones: 10 min/day tone pair drill',
        'Input: 15 min/day, Comprehensible Chinese, absolute beginner playlist',
        'Output: 3 sentences/day journal (what you did, ate, felt — using only known words)',
      ], weekend: 'Review all sentences written that week out loud.' },
      { label: 'Week 2', items: [
        'Grammar: HSK1 points #16–30',
        'Vocab: Next 25–30 HSK2 words, cumulative review of Week 1 words folded into new sentences',
        'Tones: continue drill, add shadowing 5 min/day (repeat short clips line by line)',
        'Input: 15–20 min/day, same channel, progress to next videos in sequence',
        'Output: journal grows to 4–5 sentences, start using 了 for past actions',
      ], weekend: "Record yourself reading your week's journal, listen back for tone accuracy." },
      { label: 'Week 3', items: [
        'Grammar: HSK1 points #31–50 (finishing HSK1), preview HSK2 grammar list',
        'Vocab: Next 30 words, push cumulative total toward ~150',
        'Tones: drill + shadowing 10 min combined',
        'Input: 20 min/day, mix in one graded reader alongside video',
        'Output: 5 sentences/day, attempt one linking word (因为...所以 if you\'ve hit it)',
      ], weekend: 'Self-test — cover translations, read only Chinese, see what you recall.' },
      { label: 'Week 4', items: [
        'Grammar: Finish remaining HSK1 points, start first 5–10 HSK2 points',
        'Vocab: Final push toward ~200 HSK2 words cumulative',
        'Tones: daily drill continues, should start feeling more automatic',
        'Input: 20–25 min/day, add a second input source',
        'Output: 5–8 sentences/day, attempt describing a simple planned event',
      ], weekend: "Full review — read back every journal entry from the month, note what's improved." },
    ],
    milestone: 'By end of Month 1: introduce yourself, describe your day, ask/answer simple questions without long pauses, recognize tone patterns.',
  },
  {
    month: 'Month 2', title: 'HSK2 grammar + expanding output',
    weeks: [
      { label: 'Week 5', items: [
        'Grammar: HSK2 points #1–8 (aspect particles 了/过 review, 着 introduced) — 3 sentences per point',
        'Vocab: 25–30 new words (~330 cumulative)',
        'Tones: 10 min drill + 5 min shadowing daily',
        'Input: 20–25 min/day, add an HSK2-level graded reader alongside video',
        'Output: 5–6 sentences/day, use 了 for completed actions consistently',
      ], weekend: 'Read back all Month 1 journal entries out loud, correct 3 mistakes you notice.' },
      { label: 'Week 6', items: [
        'Grammar: HSK2 points #9–16 (比 comparisons, basic complements)',
        'Vocab: 25–30 new words (~360 cumulative)',
        'Tones: 10 min drill, shadow one new clip repeated 5x',
        'Input: 25 min/day',
        'Output: 6–7 sentences/day, include one comparison sentence daily (X 比 Y...)',
      ], weekend: "Record yourself reading the week's journal, compare pace to native audio." },
      { label: 'Week 7', items: [
        'Grammar: HSK2 points #17–24 (resultative complements begin, e.g. 完/到/懂)',
        'Vocab: 25–30 new words (~390 cumulative)',
        'Tones: 10 min drill + 10 min shadowing',
        'Input: 25–30 min/day, mix reader + video',
        'Output: 7–8 sentences/day, narrate a short planned story ("tomorrow I will...")',
      ], weekend: 'Pick 5 sentences from the week, rewrite each 2 different ways.' },
      { label: 'Week 8', items: [
        'Grammar: Finish HSK2 grammar points, review all cumulative HSK1+2 grammar',
        'Vocab: Finish HSK2 vocab list (~450 cumulative)',
        'Tones: 10 min drill, shadowing 10 min',
        'Input: 30 min/day',
        'Output: 8 sentences/day, attempt a short paragraph on one topic',
      ], weekend: 'Full Month 2 review — quiz yourself on every grammar point learned so far.' },
    ],
    milestone: 'By end of Month 2: tell a simple past-tense story, compare two things, give an opinion with a reason.',
  },
  {
    month: 'Month 3', title: 'HSK3 grammar + first real conversations',
    weeks: [
      { label: 'Week 9', items: [
        'Grammar: Start HSK3 points #1–8 (把-construction introduced)',
        'Vocab: Start HSK3 list, 25–30 words (~480 cumulative)',
        'Tones: 10 min drill, continue shadowing',
        'Input: 30–35 min/day, start attempting slow native vlogs alongside graded material',
        'Speaking: book your first iTalki/HelloTalk session this week — just do it, however awkward',
        'Output: 8 sentences/day journal',
      ], weekend: "Review the week's new grammar, prep 5 questions to ask your speaking partner." },
      { label: 'Week 10', items: [
        'Grammar: HSK3 points #9–16 (more complements, 虽然...但是 concession)',
        'Vocab: 25–30 new words (~510 cumulative)',
        'Tones: 10 min drill',
        'Input: 35 min/day',
        "Speaking: 1 session (20–30 min), note 3 things you couldn't say",
        'Output: journal as usual',
      ], weekend: 'Look up how to say those 3 things, add them to your Vocab log.' },
      { label: 'Week 11', items: [
        'Grammar: HSK3 points #17–24',
        'Vocab: 25–30 new words (~540 cumulative)',
        'Tones: shadow 10 min, focus on sentence-level rhythm, not single words',
        'Input: 35–40 min/day',
        'Speaking: 2 sessions this week',
        'Output: journal as usual',
      ], weekend: 'Review any recordings from speaking sessions, note tone errors.' },
      { label: 'Week 12', items: [
        'Grammar: Finish first pass of HSK3, review weak points from weeks 9–11',
        'Vocab: 25–30 new words (~600 cumulative — HSK3 complete)',
        'Tones: 10 min drill',
        'Input: 40 min/day',
        'Speaking: 2 sessions',
        'Output: journal as usual',
      ], weekend: 'Full Month 3 review — can you hold a 10–15 min conversation? Note where it breaks down.' },
    ],
    milestone: 'By end of Month 3: hold a 10–15 min conversation on familiar topics, even if slow.',
  },
  {
    month: 'Month 4', title: 'HSK3 continued — fluency of use over correctness',
    weeks: [
      { label: 'Week 13', items: [
        'Grammar: Second pass on HSK3 — focus on your weak points from Month 3 review',
        'Vocab: Layer in sourcing/fashion/tech vocab alongside HSK3 (~630 cumulative)',
        'Tones: 10 min drill',
        'Input: 40 min/day, add learner-level podcast episodes',
        'Speaking: 3 sessions this week, steer topics toward your own interests',
        'Output: switch to voice memos 3x/week instead of only writing',
      ], weekend: "Review voice memos, write down 5 words you needed but didn't have." },
      { label: 'Week 14', items: [
        'Grammar: Continue reinforcing HSK3, notice common spoken contractions/patterns',
        'Vocab: 25–30 words (~660 cumulative), prioritize business/negotiation terms',
        'Tones: 10 min drill',
        'Input: 40 min/day',
        'Speaking: 3 sessions, try roleplaying "asking about a product" once',
        'Output: voice memos + written journal mix',
      ], weekend: "Review the week's recordings, pick one sentence to perfect." },
      { label: 'Week 15', items: [
        'Grammar: Keep reinforcing HSK3, start noticing patterns in native input unprompted',
        'Vocab: 25–30 words (~690 cumulative)',
        'Tones: 10 min drill',
        'Input: 40–45 min/day, slower native content should feel easier now',
        'Speaking: 3–4 sessions',
        'Output: voice memos 4x/week',
      ], weekend: 'Attempt a short unscripted conversation with no prep, note how it goes.' },
      { label: 'Week 16', items: [
        'Grammar: Review full HSK3 cumulative, identify any remaining gaps',
        'Vocab: 25–30 words (~720 cumulative)',
        'Tones: 10 min drill',
        'Input: 45 min/day',
        'Speaking: 3–4 sessions',
        'Output: voice memos daily if possible',
      ], weekend: 'Full Month 4 review — can you discuss your work/interests without stalling?' },
    ],
    milestone: 'By end of Month 4: discuss your work/interests, negotiate simple things, understand slower native speech.',
  },
  {
    month: 'Month 5', title: 'HSK4 begins — real-world application',
    weeks: [
      { label: 'Week 17', items: [
        'Grammar: Start HSK4 points #1–8 (bigger jump — abstract structures, formal register begins)',
        'Vocab: Start HSK4 list, 20–25 words (~750 cumulative)',
        'Tones: 10 min drill',
        'Input: 45 min/day, start reading real 1688/Alibaba Chinese listings for comprehension practice',
        'Speaking: 3–4 sessions, roleplay a sourcing negotiation scenario once',
        'Output: voice memos + written mix',
      ], weekend: "Review the week's listings, log new terms into your Vocab tab." },
      { label: 'Week 18', items: [
        'Grammar: HSK4 points #9–16',
        'Vocab: 20–25 new words (~780 cumulative), focus on negotiation/price/quality terms',
        'Tones: 10 min drill',
        'Input: 45 min/day',
        'Speaking: 3–4 sessions, try messaging a supplier in Mandarin if you can, low-stakes',
        'Output: voice memos daily',
      ], weekend: 'Review the week, redo any sentence that felt clumsy.' },
      { label: 'Week 19', items: [
        'Grammar: HSK4 points #17–24',
        'Vocab: 20–25 new words (~810 cumulative)',
        'Tones: 10 min drill',
        'Input: 45–50 min/day',
        'Speaking: 4 sessions',
        'Output: voice memos daily',
      ], weekend: 'Attempt a full transactional roleplay: inquiry → negotiation → confirmation.' },
      { label: 'Week 20', items: [
        'Grammar: Continue HSK4, review weak points',
        'Vocab: 20–25 new words (~840 cumulative)',
        'Tones: 10 min drill',
        'Input: 50 min/day',
        'Speaking: 4 sessions',
        'Output: voice memos daily',
      ], weekend: 'Full Month 5 review — can you navigate a real transactional conversation with only minor struggle?' },
    ],
    milestone: 'By end of Month 5: navigate a real transactional conversation (ordering, negotiating, clarifying specs) with some struggle but no breakdown.',
  },
  {
    month: 'Month 6', title: 'Consolidation + stress-testing',
    weeks: [
      { label: 'Week 21', items: [
        'Grammar: Continue HSK4, cumulative review of Months 1–5 grammar (spaced repetition pass)',
        'Vocab: 20–25 new words (~870 cumulative)',
        'Tones: 10 min drill',
        'Input: 50 min/day',
        'Speaking: daily if possible, minimum 4x/week',
        'Output: voice memos daily',
      ], weekend: 'Pick your weakest grammar area from the whole 6 months and drill it hard.' },
      { label: 'Week 22', items: [
        'Grammar: Finish HSK4 grammar points',
        'Vocab: 20–25 new words (~900 cumulative)',
        'Tones: 10 min drill',
        'Input: 50 min/day, attempt one full unscripted native video with only occasional pausing',
        'Speaking: daily / 4x-week',
        'Output: voice memos daily',
      ], weekend: 'Message a real supplier on 1688/WeChat yourself in Mandarin, no help.' },
      { label: 'Week 23', items: [
        'Grammar: Full HSK1–4 cumulative review',
        'Vocab: Review all Vocab log entries, drill anything shaky (~920 cumulative)',
        'Tones: 10 min drill',
        'Input: 50 min/day',
        'Speaking: daily/4x-week, attempt a 30-min unstructured conversation',
        'Output: voice memos daily',
      ], weekend: "Reflect — what's your comfortable range now vs. 6 months ago?" },
      { label: 'Week 24', items: [
        'Grammar: Final review, focus only on your personal weak points',
        'Vocab: Final push — target 1000+ words logged in your Vocab tab',
        'Tones: 10 min drill',
        'Input: 45–50 min/day',
        'Speaking: full unstructured 30-min conversation, ideally with someone new',
        'Output: voice memos daily',
      ], weekend: 'Full 6-month review — read your Week 1 journal against now. Set your next 6-month target.' },
    ],
    milestone: 'Target: conversational competence, HSK3–4 range — functional in daily and basic business contexts.',
  },
];
